---
title: "Group Project"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Packages
```{r, message=FALSE,warning=FALSE,message=FALSE}
#install.packages(c("NOISeq","ggplot2","ggfortify","ggpubr","factoextra","pca3d","dplyr","reshape2"))
library(NOISeq) # Differential analysis
library(ggplot2) # Plotting
library(ggfortify) # Plotting
library(ggpubr) # Plotting
library(factoextra) # PCA plots
library(pca3d) # PCA plots
library(dplyr) # Data manipulation
library(reshape2) # Manipulating dataframes
```

## PCA
```{r,results="hide"}
#set working directory to folder containing data files
#setwd() 

#Load FPKM data
all_gene <- read.csv("all.gene.FPKM.csv", header = T)

#Extract FPKM values and transpose
all_FPKM<-all_gene[,3:38]
all_FPKM<-t(all_FPKM)
all_FPKM<-as.data.frame(all_FPKM)

#Add small number to avoid taking log of zero, then take log of FPKM values
all_FPKM<-all_FPKM+0.25
all_FPKM<-log2(all_FPKM)

#Add factors as columns
all_FPKM$Sample<-c("A","A","A","B","B","B","C","C","C","D","D","D","E","E","E","F","F","F","A","A","A","B","B","B","C","C","C","D","D","D","E","E","E","F","F","F")
all_FPKM$Age<-c(rep("Old",18),rep("Young",18))

#Create PCA plot
all_PCA<-autoplot(prcomp(all_FPKM[1:22912]),data = all_FPKM, colour = 'Age',shape="Sample")+ggtitle("PCA on All Samples")
```

### Old-group PCA
```{r,results="hide"}
#Extract old-group FPKMs and transpose
Old_FPKM<-all_gene[,3:20]
Old_FPKM<-t(Old_FPKM)
Old_FPKM<-as.data.frame(Old_FPKM)

#Add small number to avoid taking log of zero, then take log of FPKM values
Old_FPKM<-Old_FPKM+0.25
Old_FPKM<-log2(Old_FPKM)

#Add factors as columns
Old_FPKM$Sample<-c("A","A","A","B","B","B","C","C","C","D","D","D","E","E","E","F","F","F")
Old_FPKM$Time<-c(rep(c("Baseline","2h","Trained"),6))

#Create PCA plot
Old_PCA<-autoplot(prcomp(Old_FPKM[1:22912]), x=2,y=3, data = Old_FPKM, colour = 'Time',shape="Sample")+ggtitle("PCA on Old Samples")
```

### Young-group PCA
```{r, results="hide"}
YG_FPKM<-all_gene[,21:38]
YG_FPKM<-t(YG_FPKM)
YG_FPKM<-as.data.frame(YG_FPKM)

#Add small number to avoid taking log of zero, then take log of FPKM values
YG_FPKM<-YG_FPKM+0.25
YG_FPKM<-log2(YG_FPKM)

#Add factors as columns
YG_FPKM$Sample<-c("A","A","A","B","B","B","C","C","C","D","D","D","E","E","E","F","F","F")
YG_FPKM$Time<-c(rep(c("Baseline","2h","Trained"),6))

#Create PCA plot
YG_PCA<-autoplot(prcomp(YG_FPKM[1:22912]), x=1,y=3, data = YG_FPKM, colour = 'Time',shape="Sample")+ggtitle("PCA on Young Samples")

#Put all PCA plots together
ggarrange(all_PCA,ggarrange(Old_PCA,YG_PCA, ncol =2,labels=c("B","C"),common.legend=T,legend="right"), nrow = 2,labels = "A")

#Make 3D PCA plots
all_PCA_3d<-prcomp(all_FPKM[1:22912])
all_group<-all_FPKM$Age
pca3d(all_PCA_3d, group=all_group,show.centroids = TRUE,legend ="top")

Old_PCA_3d<-prcomp(Old_FPKM[1:22912])
Old_group<-Old_FPKM$Time
pca3d(Old_PCA_3d, group=Old_group,show.centroids = TRUE,legend ="top")

YG_PCA_3d<-prcomp(YG_FPKM[1:22912])
YG_group<-YG_FPKM$Time
pca3d(YG_PCA_3d, group=YG_group,show.centroids = TRUE,legend ="top")
```

## Differential Analysis
```{r,results="hide",warning=FALSE, message=F}
#load data
YG_baseline_2h <- read.csv("YG_baseline_2h.csv", row.names=1)
YG_baseline_training <- read.csv("YG_baseline_training.csv", row.names=1)
Old_baseline_2h <- read.csv("Old_baseline_2h.csv", row.names=1)
Old_baseline_training <- read.csv("Old_baseline_training.csv", row.names=1)

#Set factors for noiseq
factors_2h<-data.frame(Time=c("xBaseline","TwoHour","xBaseline","TwoHour","xBaseline","TwoHour","xBaseline","TwoHour","xBaseline","TwoHour","xBaseline","TwoHour"))
factors_training<-data.frame(Time=c("xBaseline","Trained","xBaseline","Trained","xBaseline","Trained","xBaseline","Trained","xBaseline","Trained","xBaseline","Trained"))

#Create noiseq dataset from data and factors
YG_baseline_2h_data<-readData(data=YG_baseline_2h,factors=factors_2h)
YG_baseline_training_data<-readData(data=YG_baseline_training,factors=factors_training)
Old_baseline_2h_data<-readData(data=Old_baseline_2h,factors=factors_2h)
Old_baseline_training_data<-readData(data=Old_baseline_training,factors=factors_training)

#Run noiseq
noiseq_YG_baseline_2h<-noiseqbio(YG_baseline_2h_data,factor="Time",norm="n")
noiseq_YG_baseline_training<-noiseqbio(YG_baseline_training_data,factor="Time",norm="n")
noiseq_Old_baseline_2h<-noiseqbio(Old_baseline_2h_data,factor="Time",norm="n")
noiseq_Old_baseline_training<-noiseqbio(Old_baseline_training_data,factor="Time",norm="n")

#Extract results
YG_baseline_2h_results<-(noiseq_YG_baseline_2h@results[[1]])
YG_baseline_training_results<-(noiseq_YG_baseline_training@results[[1]])
Old_baseline_2h_results<-(noiseq_Old_baseline_2h@results[[1]])
Old_baseline_training_results<-(noiseq_Old_baseline_training@results[[1]])

#Set threshold of prob > 0.8 
YG_baseline_2h_results$threshold = as.factor(YG_baseline_2h_results$prob > 0.8)
YG_baseline_training_results$threshold = as.factor(YG_baseline_training_results$prob > 0.8)
Old_baseline_2h_results$threshold = as.factor(Old_baseline_2h_results$prob > 0.8)
Old_baseline_training_results$threshold = as.factor(Old_baseline_training_results$prob > 0.8)

#Save results
#write.csv(YG_baseline_2h_results,"YG_baseline_2h_results.csv")
#write.csv(YG_baseline_training_results,"YG_baseline_training_results.csv")
#write.csv(Old_baseline_2h_results,"Old_baseline_2h_results.csv")
#write.csv(Old_baseline_training_results,"Old_baseline_training_results.csv")

#Extract names of all DEGs
YG_baseline_2h_DEGs<-c(rownames(YG_baseline_2h_results)[which(YG_baseline_2h_results$threshold == T)])
YG_baseline_training_DEGs<-c(rownames(YG_baseline_training_results)[which(YG_baseline_training_results$threshold == T)])
Old_baseline_2h_DEGs<-c(rownames(Old_baseline_2h_results)[which(Old_baseline_2h_results$threshold == T)])
Old_baseline_training_DEGs<-c(rownames(Old_baseline_training_results)[which(Old_baseline_training_results$threshold == T)])
DEGs<-data.frame(Genes=unique(c(YG_baseline_2h_DEGs,YG_baseline_training_DEGs,Old_baseline_2h_DEGs,Old_baseline_training_DEGs)))

#Set gene IDs as a column
YG_baseline_2h_results$Genes<-rownames(YG_baseline_2h_results)
YG_baseline_training_results$Genes<-rownames(YG_baseline_training_results)
Old_baseline_2h_results$Genes<-rownames(Old_baseline_2h_results)
Old_baseline_training_results$Genes<-rownames(Old_baseline_training_results)

#Join probability, log2fc and significance of DEGs for each group
DEGs<-(left_join(DEGs,YG_baseline_2h_results[,c(4,5,6,7)]))
colnames(DEGs)<-c("Genes","YG_2h_prob","YG_2h_l2fc","YG_2h_sig")
DEGs<-(left_join(DEGs,YG_baseline_training_results[,c(4,5,6,7)]))
colnames(DEGs)<-c("Genes","YG_2h_prob","YG_2h_l2fc","YG_2h_sig","YG_training_prob","YG_training_l2fc","YG_training_sig")
DEGs<-(left_join(DEGs,Old_baseline_2h_results[,c(4,5,6,7)]))
colnames(DEGs)<-c("Genes","YG_2h_prob","YG_2h_l2fc","YG_2h_sig","YG_training_prob","YG_training_l2fc","YG_training_sig","Old_2h_prob","Old_2h_l2fc","Old_2h_sig")
DEGs<-(left_join(DEGs,Old_baseline_training_results[,c(4,5,6,7)]))
colnames(DEGs)<-c("Genes","YG_2h_prob","YG_2h_l2fc","YG_2h_sig","YG_training_prob","YG_training_l2fc","YG_training_sig","Old_2h_prob","Old_2h_l2fc","Old_2h_sig","Old_training_prob","Old_training_l2fc","Old_training_sig")
#write.csv(DEGs,"DEGs.csv",row.names = F)

#Plot log2fc and probability
g1 <- ggplot(data=YG_baseline_2h_results, aes(x=log2FC, y =prob,colour=threshold)) +geom_point() + xlab("log2 fold change") + ylab("Probability") + theme_bw() + theme(legend.position="none")+ggtitle("Differential Expression Analysis Between YG-group Baseline and 2h")+ theme(plot.title = element_text(size=10))
g2 <- ggplot(data=YG_baseline_training_results, aes(x=log2FC, y =prob,colour=threshold)) +geom_point() + xlab("log2 fold change") + ylab("Probability") + theme_bw() + theme(legend.position="none")+ggtitle("Differential Expression Analysis Between YG-group Baseline and Trained")+ theme(plot.title = element_text(size=10))
g3 <- ggplot(data=Old_baseline_2h_results, aes(x=log2FC, y =prob,colour=threshold)) +geom_point() + xlab("log2 fold change") + ylab("Probability") + theme_bw() + theme(legend.position="none")+ggtitle("Differential Expression Analysis Between Old-group Baseline and 2h")+ theme(plot.title = element_text(size=10))
g4 <- ggplot(data=Old_baseline_training_results, aes(x=log2FC, y =prob,colour=threshold)) +geom_point() + xlab("log2 fold change") + ylab("Probability") + theme_bw() + theme(legend.position="none")+ggtitle("Differential Expression Analysis Between Old-group Baseline and Trained")+ theme(plot.title = element_text(size=10))
ggarrange(g1,g2,g3,g4,nrow=2,ncol=2,labels = c("A","B","C","D"))
```

### Finding DEGs shared between groups
```{r,results="hide"}
#Import data
#DEGs <- read.csv("DEGs.csv",header = T)

#Extract log2FC of DEGs common between two groups 
Old_2h_Old_trained<-DEGs[which(DEGs$Old_training_sig == T & DEGs$Old_2h_sig == T),c(1,9,12)]
Old_2h_YG_2h<-DEGs[which(DEGs$YG_2h_sig == T & DEGs$Old_2h_sig == T),c(1,3,9)]
YG_2h_YG_trained<-DEGs[which(DEGs$YG_2h_sig == T & DEGs$YG_training_sig == T),c(1,3,6)]
YG_trained_Old_trained<-DEGs[which(DEGs$Old_training_sig == T & DEGs$YG_training_sig == T),c(1,6,12)]

#Extract log2FC of DEGs common between three groups
DEGs_3<-data.frame(Genes=as.integer(),YG_2h_l2fc=as.numeric(),YG_training_l2fc=as.numeric(),YG_training_l2fc=as.numeric(),Old_2h_l2fc=as.numeric(),Old_training_l2fc=as.numeric())
for (i in 1:1000){if ((sum(DEGs[i,]=="TRUE",na.rm=TRUE))>2) {DEGs_3<-rbind(DEGs_3,DEGs[i,c(1,3,6,9,12)])}}

#Melt dataframes to allow plotting
Old_2h_Old_trained<-melt(Old_2h_Old_trained,id="Genes")
Old_2h_YG_2h<-melt(Old_2h_YG_2h,id="Genes")
YG_2h_YG_trained<-melt(YG_2h_YG_trained,id="Genes")
YG_trained_Old_trained<-melt(YG_trained_Old_trained,id="Genes")
DEGs_3<-melt(DEGs_3,id="Genes")

#Plot log2fc for common DEGs
l2fc_p1<-ggplot(DEGs_3,aes(x=as.character(Genes),y=value,fill=variable))+geom_col()+xlab("Genes")+ylab("Log2 Fold Change")+scale_fill_manual(values=c("chartreuse1","cornflowerblue","palevioletred2","lightgoldenrod1"))+ theme(axis.text.x = element_text(angle = 90),legend.position="left") + guides(fill=guide_legend(title="Group"))
l2fc_p2<-ggplot(Old_2h_Old_trained,aes(x=as.character(Genes),y=value,fill=variable))+geom_col()+xlab("Genes")+ylab("Log2 Fold Change")+scale_fill_manual(values=c("palevioletred2","lightgoldenrod1"))+ theme(axis.text.x = element_text(angle = 90)) + guides(fill=guide_legend(title="Group"))
l2fc_p3<-ggplot(Old_2h_YG_2h,aes(x=as.character(Genes),y=value,fill=variable))+geom_col()+xlab("Genes")+ylab("Log2 Fold Change")+scale_fill_manual(values=c("chartreuse1","palevioletred2"))+ theme(axis.text.x = element_text(angle = 90,size=5)) + guides(fill=guide_legend(title="Group"))
l2fc_p4<-ggplot(YG_2h_YG_trained,aes(x=as.character(Genes),y=value,fill=variable))+geom_col()+xlab("Genes")+ylab("Log2 Fold Change")+scale_fill_manual(values=c("chartreuse1","cornflowerblue"))+ theme(axis.text.x = element_text(angle = 90,size=4)) + guides(fill=guide_legend(title="Group"))
l2fc_p5<-ggplot(YG_trained_Old_trained,aes(x=as.character(Genes),y=value,fill=variable))+geom_col()+xlab("Genes")+ylab("Log2 Fold Change")+scale_fill_manual(values=c("cornflowerblue","lightgoldenrod1"))+ theme(axis.text.x = element_text(angle = 90,size=4)) + guides(fill=guide_legend(title="Group"))

ggarrange(l2fc_p1,l2fc_p2,l2fc_p3,l2fc_p4,l2fc_p5,ncol=3,nrow=2,common.legend=T,labels=c("A","B","C","D","E"))

```
